@HappyFactory_HostAddress = http://localhost:5116

### Create product and capture id (robust JSON handling)
POST {{HappyFactory_HostAddress}}/products
Content-Type: application/json

{
  "name": "Toy Car",
  "sku": "TOYCAR-001"
}

> {%
    client.global.set("created-product-id", response.body.id);
%}

### Get the created product using the captured id
GET {{HappyFactory_HostAddress}}/products/{{created-product-id}}
Accept: application/json

### Invalid GUID example (shows validation/error response)
GET {{HappyFactory_HostAddress}}/products/00000000-0000-0000-0000-000000000000
Accept: application/json
